export const fa = {
    login: "ورود",
    register: "ثبت نام",
    sign_in: 'ورود',
    Sign_out:'خروج از سیستم',
    app_title: 'ادمین کاتد',
    app_title_: 'عنوان برنامه',
    app_logo: 'ادمین کاتد',
    brand_name: 'ادمین کاتد',
    dashboard: 'داشبورد',


    




    sign_in_bookstore_account: 'با حساب فروشگاه کتاب خود داخل شوید',
    forgot_password: 'رمز عبورتان را فراموش کردید؟',
    msg: {
        ui: {
            msg1: 'عملیات با موفقیت انجام شد.',
            msg2: 'خطا رخ داد.',
            msg3: 'ثبت نام با موفقیت انجام شد، به صفحه ورود منتقل می شوید.',
            msg4: 'رمز عبور با موفقیت تغییر کرد، به صفحه ورود منتقل می شوید.',
            your_rate_submited: 'رتبه شما ثبت شد',
            your_comment_submited: 'نظر شما ثبت شد',
            your_comment_will_be_removed_continue: 'نظر شما حذف خواهد شد، تایید می کنید؟',
            no_network_connection: 'خطا رخ داد، لطفا دسترسی اینترنت خود را بررسی کرده و مجددا تلاش کنید.',
            new_vesion_available_update: 'نسخه جدیدی از برنامه موجود است، می توانید آن را بروز کنید.',
            item_will_be_removed_continue: 'رکورد مورد نظر حذف خواهد شد، تایید می کنید؟',
            your_purchase_completed: 'خرید شما تکمیل شد',
            your_collection_will_be_removed_continue: 'حذف کلکسیون، کتاب های موجود در آن را حذف نخواهد کرد.',
            your_collection_will_be_downloaded_continue: 'همه کتاب های این کلکسیون دانلود می شود.',
            file_could_not_be_uploaded: 'فایل قابل آپلود نیست.',
            file_could_not_be_uploaded_max_size_n: 'فایل قابل آپلود نیست، حداکثر اندازه {0} است',
            profile_img_not_uploaded_max_size_n:'فایل قابل آپلود نیست، فقط "تصویر" و با اندازه ای کمتر از "{0}" انتخاب کنید',
            one_img_upload_allowed_remove_existing_one: "تنها می توانید یک تصویر بارگذاری کنید، لطفا عکس فعلی را حذف کنید.",
            login_again: 'مجددا وارد شوید',
            sync_error: 'هنگام همگام سازی خطایی روی داد',
            logout_erase_user_data_warning: 'با خروج از برنامه، همه اطلاعات این کاربر، از این دستگاه حذف می شود.',
            book_file_not_found_download_it: 'فایل کتاب پیدا نشد، لطفا آن را دانلود کنید.',
            reader_epub_error_occurred: 'در هنگام نمایش کتاب خطا رخ داد',
            reader_audio_error_occurred: 'در هنگام پخش کتاب خطا رخ داد',
            change_password_successful: 'رمز عبور با موفقیت بروز شد',
            downloading_reader_security_content: 'در حال بارگذاری سامانه امنیت محتوا، لطفا لحظاتی بعد مجددا تلاش کنید.',
            initing_reader_security_content: 'در حال آماده سازی سامانه امنیت محتوا، لطفا لحظاتی بعد مجددا تلاش کنید.',
            reader_security_content_failed: 'سامانه امنیت محتوا با خطا مواجه شد. لطفا برنامه را مجددا بارگیری نمائید',
            clear_general_content: 'فایل های ذخیره شده مانند: html، عکس های پیشفرض و js پاک خواهد شد.',
            reset_reader: 'تازه سازی کتابخوان: اندازه قلم، رنگ، شدت صدا و...',
            book_x_file_not_exist: 'کتاب {0} فایلی برای دانلود ندارد',
            book_x_sampleFile_not_exist: 'کتاب {0} فایل نمونه ای برای دانلود ندارد',
            book_x_file_problem: "فایل کتاب {0} خراب است و قابل بارگیری نیست",
            device_key_not_found_reload: 'دستگاه شما هنوز ثبت نشده است، لطفا از اتصال اینترنت خود مطمئن شده و برنامه را مجددا بارگیری نمائید',
            you_reached_maximum_active_device: 'شما به سقف مجاز تعداد دستگاه های فعال رسیدید، لطفا حداقل یکی از آن ها را حذف کنید',
            delete_device_will_logout: 'با حذف هر مورد، دستگاه مورد نظر از سامانه خارج شده و اطلاعات کاربری از قبیل فایل های دانلود شده مرتبط با کاربر، پاک خواهد شد.',
        },
        back: {
            user_already_exists: 'کاربر از قبل وجود دارد.',
            no_valid_activation_code: 'کد فعالسازی شما منقضی شده است، برای دریافت کد جدید ارسال مجدد را بفشارید.',
            wrong_activation_code: 'کد فعالسازی اشتباه است.',
            already_has_valid_key: 'امکان ارسال مجدد پیامک {0} ثانیه دیگر برای شما فعال می شود.',
            message_not_sent: 'ارسال پیامک با خطا مواجه شد، لطفا مجددا تلاش کنید.',
            cell_no_required: 'تلفن همراه الزامی است.',
            message_sent: 'پیام با موفقیت برای تلفن همراه ارسال شد.',
            username_exists: 'نام کاربری تکراری است، لطفا نام کاربری دیگری انتخاب کنید.',
            signup_token_not_exists: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            invalid_signup_token: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            token_invalid: 'مجددا وارد شوید',
            token_expired: 'مجددا وارد شوید',
            delete_failed: 'خطا در حذف اطلاعات از سرویس دهنده رخ داد.',
            get_failed: 'خطا در دریافت اطلاعات از سرویس دهنده رخ داد.',
            auth_decoding_failed: 'Authentication decoding failed',
            commit_failed: 'سرویس دهنده با خطا مواجه شد.',
            no_auth: 'شما وارد نشده اید',
            invalid_username: 'نام کاربری یا رمز عبور اشتباه است.',
            invalid_enum: 'enum is not correct  type',
            not_found: 'مورد، یافت نشد.',
            invalid_persons: 'there is invalid person id in list',
            addition_error: 'adding model to database failed',
            username_cellno_required: 'برای دریافت رمز عبور نام کاربری یا شماره موبایل را وارد کنید',
            invalid_user: "با اطلاعات وارد شده کاربری وجود ندارد",
            invalid_code: 'کد تایید اشتباه است.',
            filter_required: 'filter object is not in data',
            upload_failed: 'بارگذاری فایل با مشکل مواجه شد.',
            invalid_entity: 'خطا از سرویس دهنده رخ داد.',
            access_denied: 'دسترسی به این مورد امکانپذیر نمی باشد',
            already_liked: 'شما قبلا این نظر را مفید اعلام کردید.',
            comment_not_found: 'نظر یافت نشد.',
            already_reported: ' شما قبلا این نظر را گزارش کردید.',
            report_not_found: 'گزارشی از شما برای این نظر یافت نشد.',
            parent_not_found: 'نظر مرتبط با این نظر یافت نشد.',
            follow_denied: 'کاربر نمی تواند خودش را دنبال کند.',
            already_follows: 'شما از قبل این مورد را دنبال کرده اید.',
            missing_requiered_field: 'موارد ضروری را پر کنید',
            already_rated: 'کاربر از قبل به کتاب رتبه داده است.',
            already_exists: 'از قبل وجود دارد.',
            credit_debit_error: 'اعتبار و بدهی هر دو نمی تواند همزمان مقدار داشته باشد.',
            no_price_found: 'برای کتاب قیمتی وجود ندارد.',
            discount_is_float: 'تخفیف باید عدد وارد شود.',
            insufficiant_balance: 'موجودی حساب شما از رسید کمتر است',
            user_has_no_account: 'کاربر حسابی ندارد',
            order_invoiced: 'سفارش فاکتور شده و قابل حذف نمی باشد.',
            commit_error: 'خطا در نوع داده ارسالی',
            person_has_books: 'این شخص در حال حاظر نقش در کتاب(ها) دارد.',
            book_not_in_lib: 'کتاب در کتابخانه شما وجود ندارد و نمی توان آن را به کلکسیونی افزود.',
            online_book_count_limitation: 'فقط کتاب چاپی و DVD تعداد بیشتر از 1 می پذیرد.',
            recheck_information: ".خطایی در دادههای ارسالی وجود دارد، لطفا اطلاعات را بررسی کنید و دوباره ارسال نمایید. (درخواست پرداخت)",
            analyzing_error: "خطایی در تحلیل دادههای در سرور کیپو بوجود آمده است، دقایقی دیگر امتحان فرمایید.",
            server_connection_error: "امکان برقراری ارتباط با سرور کیپو میسر نمیباشد.",
            sending_data_error: "خطایی در دادههای ارسالی وجود دارد، لطفا اطلاعات را بررسی کنید و دوباره ارسال نمایید. (بررسی تایید پرداخت)",
            payment_canceled: "پرداخت توسط کاربر لغو شده یا با مشکل مواجه شده است",
            buyer_cell_no_error: "شماره تماس فروشنده مورد نظر مورد تایید نمیباشد.",
            minimum_payment_error: "حداقل مبلغ پرداخت 1,000 ریال میباشد.",
            maximum_payment_error: "حداکثر مبلغ پرداخت 30,0000,000 ریال میباشد.",
            payment_serial_error: "شناسه پرداخت ارسالی مورد تایید نمیباشد.",

            invalid_shopping_key: 'shopping key is invalid',
            payment_already_considered: 'payment already considered',
            payment_inquiry_invalid: 'payment inquiry invalid',
            payment_bank_response_invalid: 'payment bank response invalid',
            app_config_required: 'app config required',
            in_process: 'in process',
            maximum_active_device: 'شما به سقف مجاز تعداد دستگاه های فعال رسیدید، لطفا حداقل یکی از آن ها را حذف کنید',
            invalid_password: 'رمز عبور اشتباه است',
            content_format_invalid: 'content format invalid',
            book_not_generated: 'book not generated',
            used_somewhere: 'used somewhere',
            book_has_no_content: 'برای کتاب محتوایی موجود نیست',
            invalid_device: 'invalid device',
            RID_opration_failed: 'RID opration failed',
            schema_not_valid: 'الگو ارسالی معتبر نیست',
        }
    },
    validation: {
        minLength: 'حداقل {value} کاراکتر',
        mobileFormat: 'فرمت موبایل صحیح نیست',
        smsCodeFormat: 'فرمت کد صحیح نیست.',
        confirmPassword: 'رمز عبور با تایید آن همخوانی ندارد.',
        emailFormat: 'فرمت ایمیل صحیح نیست',
        phoneFormat: 'فرمت تلفن صحیح نیست',
    },
    username: 'نام کاربری',
    password: 'رمز عبور',
    name: 'نام',
    lastname: 'نام خانوادگی',
    phone: 'تلفن',
    address: 'آدرس',
    mobile: 'تلفن همراه',
    email: 'ایمیل',
    confirm_password: 'تایید رمز عبور',
    old_password: 'رمز عبور قبلی',
    new_password: 'رمز عبور جدید',
    confirm_new_password: 'تایید رمز عبور جدید',
    invalid_value: 'مقدار نامعتبر است',
    required_field: 'فیلد ضروری است',
    Show_password: 'نمایش رمزعبور',
    login_agree_msg: {
        a: 'با انتخاب "ورود" شما موافقت خود با {0} و {1} را تایید می کنید.',
        b: 'مطالب فروشگاه کتاب',
        c: 'شرایط استفاده از نرم افزار'
    },
    new_to_Bookstore: 'تازه واردید؟',
    need_free_bookstore_account: "احتیاج به یک حساب کاربری رایگان فروشگاه کتاب دارید.",
    register_your_mobile_number: 'شماره تلفن همراه خود را وارد کنید',
    submit: 'ثبت',
    already_have_bookstore_account: 'از قبل حساب کاربری فروشگاه کتاب دارید؟',
    verification_code_sended_via_sms_submit_here: 'کد تایید برای شما پیامک شد، لطفا در اینجا ثبت کنید.',
    verification_code: 'کد تایید',
    create_an_account: 'ساخت حساب کاربری',
    send_again: 'ارسال مجدد',
    send_again_activationCode: 'ارسال مجدد کد فعالسازی',
    in: 'در',
    second: 'ثانیه',
    search: 'جستجو',
    home: 'خانه',
    library: 'کتابخانه',
    store: 'فروشگاه',
    more: 'بیشتر',
    recomended_for_you: 'پیشنهادی برای شما',
    new_release_in_bookstore: 'نسخه های جدید در کتابفروشی',
    more_by_writer: 'بیشتر از {0}',
    helen_hardet: 'هلن هاردت',
    it_will_be_launched_soon: 'بزودی راه اندازی خواهد شد.',

    read_now: 'الان بخوان',
    view_in_store: 'نمایش در فروشگاه',
    add_to_collection: 'اضافه کردن به کلکسیون',
    mark_as_read: 'به عنوان خوانده شده علامت بزن',
    mark_as_unRead:'به عنوان خوانده نشده علامت بزن',
    share_progress: 'اشتراک گذاری پیشرفت',
    recommend_this_book: 'پیشنهاد دادن کتاب',
    remove_from_device: 'حذف از دستگاه',
    remove_from_home: 'حذف از خانه',
    loading_with_dots: 'درحال بارگذاری...',
    retry: 'تلاش مجدد',
    title: 'عنوان',
    return: 'بازگشت',
    insert_username_or_mobile: 'نام کاربری یا شماره تلفن همراه خود را وارد کنید',
    reset_password: 'تغییر رمز عبور',
    add_to_list: 'به لیست اضافه کن',
    log_out: 'خروج',
    sync: 'همگام سازی',
    syncing: 'در حال همگام سازی',
    syncing_with_dots: 'در حال همگام سازی...',
    last_synced_on: 'آخرین همگام سازی در',
    read_listen_with_audible: 'خواندن و گوش دادن با صدا',
    book_update: 'بروزرسانی کتاب',
    reading_insights: 'خواندن عمیق',
    settings: 'تنظیمات',
    info: 'اطلاعات',
    help_feedback: 'کمک و بازخورد',
    about_bookstore_edition: 'درباره نسخه کتابفروشی',
    Length: 'اندازه',
    pages: 'صفحه',
    from_the_editor: 'از ویراستار',
    about_this_item: 'درباره این محصول',

    description: 'توضیحات',
    product_description: 'توضیحات محصول',
    review: 'نظر',
    reviews: 'نظرات',
    review_s: 'نظر',
    about_the_author: 'درباره نویسنده',
    features_details: 'ویژگی ها و جزئیات',
    product_details: 'جزئیات محصول',
    publication_date: 'تاریخ انتشار',
    publisher: 'ناشر',
    language: 'زبان',
    bookstore_sales_rank: 'رتبه فروش در کتابفروشی',
    follow: 'دنبال کردن',
    unfollow: 'دنبال نکردن',
    customer_review: 'نظر مشتری ها',
    customer_vote_s: 'رای مشتری ها',
    read_reviews_that_mention: 'خواندن نظر های ذکر شده',
    see_more: 'بیشتر ببینید',
    see_less: 'کمتر ببینید',
    top_reviews: 'نظر های برتر',
    verified_purchase: 'خرید تایید شده',
    format: 'قالب',
    bookstore_edition: 'نسخه کتابفروشی',
    people_found_this_helpful: 'نفر این مورد را مفید یافتند',
    people_found_this_helpful_1: 'نفر این مورد را مفید یافت',
    people_report_this: 'نفر این مورد را گزارش کردند',
    people_report_this_1: 'نفر این مورد را گزارش کرد',
    helpful: 'مفید است',
    report: 'گزارش',
    see_all_n_reviews: 'دیدن همه {0} نظر',
    write_a_review: 'یک نظر بگذارید',
    n_out_of_m_stars: '{0} از {1} ستاره',
    bookstore_books: 'کتاب های کتابفروشی',
    best_seller: 'پرفروش ها',
    more_to_explore: 'بیشتر برای کاوش',
    all: 'همه',
    downloaded: 'دانلود شده',
    more_reviews: 'نظرات بیشتر',
    thank_you_for_your_feedback: 'با تشکر از بازخورد شما',
    inspired_by_your_wishlist: 'با توجه به لیست علاقه مندی های شما',
    uncollected: 'بدون دسته',
    of: 'از',
    from: 'از',
    to: 'تا',
    customer_reviews: 'نظرات مشتری ها',
    by_writerName: 'از',
    agent: 'نماینده',
    previous: 'قبلی',
    next: 'بعدی',
    no_item_found: 'موردی یافت نشد',
    category: {
        category: 'گروه',
        new: 'نسخه های جدید',
        best_seller: 'پرفروش ها',
        recommended: 'پیشنهادی برای شما',
        wishlist: 'لیست علاقه مندی ها',

        romance: 'عاشقانه',
        classic: 'کلاسیک',
        comedy: 'کمدی',
        drama: 'درام',
        historical: 'تاریخی',
        religious: 'مذهبی',
        science: 'علمی',
        social: 'اجتماعی',
    },
    load_more: 'بارگذاری بیشتر',
    book_isben: 'شابک',
    your_comment: 'نظر شما',
    remove: 'حذف',
    your_report_submited: 'گزارش شما ثبت شد',
    vote: 'رای',
    vote_s: 'رای',
    votes: 'آراء',
    remove_from_list: 'از لیست حذف کن',
    recent_reviews: 'نظرات اخیر',
    minute: 'دقیقه',
    hour: 'ساعت',
    remove_comment: 'حذف نظر',
    close: 'بستن',
    app_info: 'اطلاعات برنامه',
    version: 'نسخه',
    version_mode: 'نوع نسخه',
    trial_mode: 'نسخه آزمایشی',
    trial: 'آزمایشی',
    dont_want_now: "فعلا نمی خواهم",
    update: 'بروزرسانی',
    shopping_cart: 'سبد خرید',
    remove_from_wish_list: 'از لیست علاقه مندی ها حذف کن',
    add_to_wish_list: 'به لیست علاقه مندی ها اضافه کن',
    remove_from_cart_list: 'از سبد خرید حذف کن',
    add_to_cart_list: 'به سبد خرید اضافه کن',
    your_shopping_cart_is_empty: 'سبد خرید شما خالیست',
    book_type: 'نوع کتاب',
    genre_type_list: {
        Comedy: "کمدی",
        Drama: "درام",
        Romance: "رمان",
        Social: "اجتماعی",
        Religious: "دینی",
        Historical: "تاریخی",
        Classic: "کلاسیک",
        Science: "علمی",
    },
    book_type_list: {
        DVD: 'دی وی دی',
        Audio: 'صوتی',
        Hard_Copy: 'چاپی',
        Pdf: 'پی دی اف',
        Epub: 'Epub',
        Msd: 'کتابخوان'
    },
    role_type_list: {
        Author: 'مولف',
        Writer: 'نویسنده',
        Translator: 'مترجم',
        Press: 'مطبوعات',
        Contributer: 'مشارکت کننده',
        Designer: 'طراح',
    },
    buy: 'خرید',
    price: 'قیمت',
    total_price: 'قیمت کل',
    recalculate: 'محاسبه مجدد',
    view_detail: 'نمایش جزئیات',
    cancel: 'انصراف',
    ok: 'تایید',
    create: 'ایجاد',
    new_collection: 'کلکسیون جدید',
    collection_name: 'نام کلکسیون',
    create_new_collection: 'ایجاد کلکسیون جدید',
    remove_collection: 'حذف کلکسیون',
    delete_collection_: 'کلکسیون حذف شود؟',
    rename_collection: 'تغییر نام کلکسیون',
    rename: 'تغییر نام',
    download_collection: 'دانلود کلکسیون',
    download_collection_: 'کلکسیون دانلود شود؟',
    download: 'دانلود',
    downloading: 'درحال دانلود',
    add: 'افزودن',
    selected: 'انتخاب شده',
    select_all: 'انتخاب همه',
    deselect_all: 'لغو انتخاب همه',
    profile: "پروفایل",
    profile_image: "تصویر پروفایل",
    exist_in_library: 'موجود در کتابخانه',
    preview: "پیش نمایش",
    drag_and_drop: "بکشید و رها کنید",
    choose_image: 'انتخاب تصویر',
    n_min_left_in_chapter: '{0} دقیقه از فصل مانده است',
    n_min_left_in_book: '{0} دقیقه از کتاب مانده است',
    book_from_your_library: 'کتاب از کتابخانه شما',
    your_recent_item_appear_manage_remove: 'کتاب اخیر شما در اینجا ظاهر می شود. شما می توانید آن را در هر زمان مدیریت یا حذف کنید. ',
    go_to_library: 'رفتن به کتابخانه',
    shop_in_store: 'خرید از فروشگاه',
    sure_you_want_log_out: 'آیا برای خروج از برنامه مطمئن هستید؟',
    readed_: 'خوانده شده',
    close_book: 'بستن کتاب',
    goto: 'برو به',
    go: 'برو',
    enter_location: 'مکان را وارد کنید',
    you_are_reading_loaction_n: 'شما اکنون مکان {0} را می خوانید.',
    purchase_history: 'تاریخچه خرید',
    purchase_date: 'تاریخ خرید',
    page_not_found: 'صفحه یافت نشد',
    detail: 'جزئیات',
    count: 'تعداد',
    unit_price: 'قیمت واحد',
    type: 'نوع',
    text_size: 'اندازه قلم',
    theme: 'تم',
    font: 'فونت',
    reader_theme_obj: {
        white: 'سفید',
        dark: 'سیاه',
        green: 'سبز',
        sepia: 'سوبیایی',
    },
    font_obj: {
        iransans: 'ایرانسنس',
        nunito: 'نونیتو',
        zar: 'زر',
    },
    account_balance: 'موجودی حساب',
    increase_credit: 'افزایش اعتبار',
    payment: 'پرداخت',
    existing_credit: 'اعتبار موجود',
    increase_amount_rial: 'مبلغ افزایش (ریال)',
    min_increase_amount_rial_is: 'حداقل مبلغ افزایش {0} ریال است.',
    payment_status_obj: {
        successful: 'پرداخت با موفقیت انجام شد.',
        'payment-canceled': 'پرداخت لغو شد.',
        unknown: 'خطا در پرداخت اتفاق افتاد.',
        'payment-amount-invalid': 'مقدار پرداخت صحیح نیست.',
    },
    payment_result: 'نتیجه پرداخت',
    language_obj: {
        PERSIAN: 'فارسی',
        ENGLISH: 'انگلیسی',
        ARABIC: 'عربی',
        FRENCH: 'فرانسوی',
        GERMAN: 'آلمانی',
        SPANISH: 'اسپانیایی',
    },
    change_password: 'تغییر رمز عبور',
    storage: 'مخزن',
    clear_general_content: 'پاکسازی محتوا عمومی',
    clear_content_security_system: 'پاکسازی سیستم امنیت محتوا',
    state: 'وضعیت',
    reset_reader: 'تازه سازی کتابخوان',
    confirm: 'تایید',
    javscript_file: 'فایل جاوااسکریپت',
    webassembly_file: 'فایل وب اسمبلی',
    clear: 'پاک کن',
    unknown: 'نامشخص',
    operating_system: 'سیستم عامل',
    browser: 'مرورگر',
    device: 'دستگاه',
    active_device_list: 'لیست دستگاه های فعال',
    submit_this_device: 'ثبت این دستگاه',
    this_device: 'این دستگاه',
    zoom: 'بزرگنمایی',
    reload_app: 'بارگیری مجدد برنامه',
    compatible_browsers: 'مرورگرهای سازگار',
    app_compatible_browsers_: 'دستگاه های دسکتاپ و یا حاوی سیستم عامل اندروید: "مرورگر کروم"؛ دستگاه حاوی سیستم عامل IOS: "مرورگر سافاری"',
    show_book_sample: 'نمایش نمونه کتاب',
    play_book_sample: 'پخش نمونه کتاب',
    download_book_sample: 'دانلود نمونه کتاب',
}